services:
  app:
    build: .
    ports:
      - "2303:2303"
    volumes:
      - ./config.yml:/config.yml
    depends_on:
      - postgres
  postgres:
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: film_upload
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: salam_news